version: '3.8'
services:
  server:
    container_name: server
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - trader-api
      - verification-api
      - bitcoin-api
  db:
    container_name: db
    image: mongo
    environment:
      - PORT=27017
    volumes:
      - /data-vol:/data/traderapiv1
      - /data-vol:/data/apiswissnordic
      - /data-vol:/data/verificationapi

  trader-api:
    container_name: trader-api
    restart: always
    build: ./trader_api
    environment:
      - PORT=8001

  verification-api:
    container_name: verification-api
    restart: always
    build: ./verification_api
    environment:
      - PORT=8081

  bitcoin-api:
    container_name: bitcoin-api
    restart: always
    build: ./bitcoin_api
    environment:
      - PORT=8084
